config/routes.rb
Rails.application.routes.draw do


  get 'articles/show/:id', to: 'articles#show', as: 'article_show'
  get 'articles/:id/comment/new/', to: 'comments#new', as: 'new_comment'

  post 'comments/', to: 'comments#create', as: 'create_comment'
  root to: 'articles#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord

  has_many :comments

end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :article

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
    @articles = Article.all
  end

  def create
    @comment = Comment.create(author: params[:author],content: params[:content], article_id: params[:article_id])
    redirect_to root_path
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/index.html.erb
<div class="col-md-4 col-md-offset-4">
  <h1>Liste des articles</h1>
</div>

<table class="table table-bordered col-md-12">
  <tr>
    <th>#</th>
    <th>Titre</th>
    <th>Option</th>
  </tr>
  <% @articles.each do |article| %>
  <tr>
    <th><%= article.id %></th>
    <td><%= article.title %></td>
    <td><%= link_to "Montrer l'article", article_show_path(article.id), class: "btn btn-primary" %></td>
  </tr>
  <% end %>

</table>

app/views/articles/show.html.erb
<div class="row">
  <div class="col-md-6">
    <h1>Informations sur l'article</h1>
  </div>
</div>

<div class="row">
  <div class="col-md-6">
    <p><strong>ID</strong>: <%= @article.id %></p>
    <p><strong>Titre</strong>: <%= @article.title %></p>
    <p><strong>Contenu</strong>: <%= @article.content %></p>
    <%= image_tag(@article.fun,height: '120', width: '120' ) %>

  </div>
</div>

<div class="row">
  <div class="col-md-6">
    <% @article.comments.each do |comment| %>
      <p><%= comment.author %></p>
      <p><%= comment.content %></p>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="col-md-6">
  <%= link_to "Créer un commentaire", new_comment_path(@article.id), class: "btn btn-primary" %>

  <%= link_to "Accueil", root_path, class: "btn btn-success" %>
  </div>
</div>

app/views/comments/_form.html.erb
<%= form_tag(create_comment_path, method: :post) do %>

  <div class="form-group">
    <label for="author">Auteur:</label>
    <br>
    <input type="text" name="author" id="author" placeholder="auteur" />
  </div>
  <div class="form-group">
    <label for="content">Commentaire:</label>
    <br>
    <textarea name="content" id="content" cols="20" rows="10"></textarea>
  </div>

  <div class="form-group">
    <label for="article_id">Article :</label>
    <select name="article_id">
      <% @articles.each do |article| %>
        <option value="<%= article.id %>"><%= article.title %></option>
      <% end %>
    </select>
  </div>
    <input type="submit" value="Ajouter un commentaire" class="btn btn-primary">
  </div>

<% end %>

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/comments/edit.html.erb
<h1>Comments#edit</h1>
<p>Find me in app/views/comments/edit.html.erb</p>

app/views/comments/new.html.erb
<div class="row">
  <h1> Laissez un commentaire ! </h1>
</div>


<div class="row">
  <div class="col-md-6">
   <%= render partial: "form" %>
   </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>